---
- name: setup localhost
  hosts: localhost
  connection: local
  vars_files:
    - roles/homebrew/vars/homebrew.yml
    - roles/defaults/vars/defaults.yml
  roles:
    - validation
    - homebrew
    - dotfiles
    - configs
