---
- name: setup localhost
  hosts: localhost
  connection: local
  vars_files:
    - vars/homebrew.yml
    - vars/defaults.yml
  roles:
    - validation
    - homebrew
    - dotfiles
    - configs
    - defaults
